version: '3.7'

services:
  dbpostgres:
    image: arm64v8/postgres:11.21-alpine3.17
    container_name: ps_database
    restart: always
    ports:
      - 9000:5432
    environment:
      POSTGRES_PASSWORD: david
      POSTGRES_USER: david
      POSTGRES_MULTIPLE_DATABASES: chatbot  # Corrected typo
    volumes:
      - ./backend/database_store/chatbot:/var/lib/postgresql/data
  
  econ_chat_frontend:
    image: samdobson/streamlit
    container_name: econ_chat_frontend
    build: 
      context: ./streamlit_app
    ports:
      - 8501:8501
    volumes:
      - ./streamlit_app:/app

  econ_chat_backend:
    container_name: econ_chat_backend
    build: 
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    links:
      - dbpostgres
    depends_on:
      - dbpostgres